---
_script: &PACKAGE_APP_SCRIPT
    driver:
      # Package the app for the test. Extra checks are necessary because we _must_ use GNU Tar for extracting in Windows.
      pre_create_command: |
        echo '## Packing test app...'
        case "$(uname -s)" in
          Darwin)
            echo '## Mac detected, using gtar'
            command -v gtar >/dev/null 2>&1 || { echo "You need to install gnu-tar to test app_upgrade. 'brew install gnu-tar'" >&2; exit 1; }
            gtar -czvf test/files/pkg-app.spl -C test/files test_app
            ;;
          *)
            echo '## Using tar'
            tar -czvf test/files/pkg-app.spl -C test/files test_app
            ;;
        esac

driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.16
  data_path: test/files

platforms:
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-8.4
  - name: windows
    driver:
      box: mwrock/Windows2012R2
      gui: false # The default is true because consumers of this box generally use the GUI.

suites:
  - name: install
    run_list:
      - recipe[cerner_splunk_ingredient_test::splunk]
  - name: uninstall
    run_list:
      - recipe[cerner_splunk_ingredient_test::splunk]
      - recipe[cerner_splunk_ingredient_test::uninstall_splunk]
  - name: install_forwarder
    <<: *PACKAGE_APP_SCRIPT
    run_list:
      - recipe[cerner_splunk_ingredient_test::universal_forwarder]
  - name: uninstall_forwarder
    run_list:
      - recipe[cerner_splunk_ingredient_test::universal_forwarder]
      - recipe[cerner_splunk_ingredient_test::uninstall_universal_forwarder]
  - name: archive_install
    run_list:
      - recipe[cerner_splunk_ingredient_test::splunk_archive]
  - name: archive_uninstall
    run_list:
      - recipe[cerner_splunk_ingredient_test::splunk_archive]
      - recipe[cerner_splunk_ingredient_test::uninstall_splunk_archive]
  - name: app_upgrade
    <<: *PACKAGE_APP_SCRIPT
    run_list:
      - recipe[cerner_splunk_ingredient_test::splunk]
      - recipe[cerner_splunk_ingredient_test::upgrade_splunk_app]

verifier:
  name: inspec
