AllCops:
  Exclude:
    - 'vendor/**/*'
  TargetRubyVersion: 2.1

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Documentation:
  Enabled: false
